// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL=https://<project-ref>.supabase.co
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY=REDACTED_SUPABASE_ANON_KEY

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Determine correct redirect URL based on environment
export const getRedirectUrl = () => {
  if (typeof window === 'undefined') return 'https://dashboard.lanonasis.com/auth/callback';

  const isLocalDevelopment = window.location.hostname === '127.0.0.1' ||
    window.location.hostname === 'localhost' ||
    window.location.hostname.match(/^192\.168\./);

  if (isLocalDevelopment) {
    return `${window.location.origin}/auth/callback`;
  }

  // Always redirect to dashboard.lanonasis.com auth callback for OAuth
  return 'https://dashboard.lanonasis.com/auth/callback';
};

// OAuth callback URL for provider configurations
export const getOAuthCallbackUrl = () => {
  if (typeof window === 'undefined') return 'https://dashboard.lanonasis.com/auth/callback';

  const isLocalDevelopment = window.location.hostname === '127.0.0.1' ||
    window.location.hostname === 'localhost' ||
    window.location.hostname.match(/^192\.168\./);

  if (isLocalDevelopment) {
    return `${window.location.origin}/auth/callback`;
  }

  // Always use dashboard.lanonasis.com for OAuth callbacks
  return 'https://dashboard.lanonasis.com/auth/callback';
};

// Create Supabase client with error handling
let supabaseClient;
try {
  supabaseClient = createClient<Database>(
    SUPABASE_URL=https://<project-ref>.supabase.co
    SUPABASE_PUBLISHABLE_KEY,
    {
      auth: {
        flowType: 'pkce',
        detectSessionInUrl: true,
        persistSession: true,
        autoRefreshToken: true,
      },
    }
  );
} catch (error) {
  console.error('Failed to initialize Supabase client:', error);
  // Create a dummy client that won't crash the app
  supabaseClient = createClient<Database>(
    'https://placeholder.supabase.co',
    'placeholder-key'
  );
}

export const supabase = supabaseClient;